# Introduction

Welcome to measure theory. This course introduces the modern theory of functions and integration which underpins most advanced analysis topics. In particular the theory of function spaces will be important in PDEs and the notion of measurable functions allows us to rigorously understand random variables. 

The key example we will study is **Lebesgue measure** in $\mathbb{R}^d$. The goal of defining Lebesgue measure is to find a way of asigning length/area/volume/whatever its called if $d \geq 4$ to a subset of $\mathbb{R}^d$. It turns out that it is not possible to do this for every possible subset of $\mathbb{R}^d$, but it is possible to do this for every subset you are likely to come across!


## Integration

One of the most important results of measure theory is the ability to integrate `against' the measures that we define. We want this new definition of the integral to agree with the Riemann integral on subsets of $\mathbb{R}^d$ and also allow us to integrate over sets that aren't subsets of $\mathbb{R}^d$ or with different weightings of the different parts of $\mathbb{R}^d$. This new theory of integration allows us to rigorously define expectation in probability theory and provides numerous convergence theorems which are some of the results you will use most from this course.


## The most important things you will learn in this course

For your own knowledge of how measure and function `really' work:

- How Lebesgue measure is constructed.
- How the Lebesgue integral is constructed.
- How product measures/spaces are constructed.
- How $L^p$ spaces are defined.


For use in later courses:

- The fact that Lebesgue measure exists and does what you expect it to do.
- Why you can work with measures just by looking at how they behave on a $\pi$-system (find out what that is soon!).
- The different ways in which functions can converge.
- Equivalences between ways things converge.
- Convergence theorems: i.e. when convergence of functions implies convergence of their integrals (dominated convergence and monotone convergence).
- Important inequalities: Hölder/Cauchy-Schwartz, Minkowski, Jensen.
- When you can switch the order of integration.


