# sigma-algebras, definition of a measure

We are going to begin by learning the basic definitions of measure and the different types of collections of subsets that are important in the theory. While this is fairly dry and unmotivated it is relatively straightforward and provides a good foundation for the rest of the course. You should think about this section like you would think about learning the group axioms before learning any specific use group theory would be put to.

## Collections of subsets

We begin with some dry definitions of collections of sets and functions from collections of sets to $\mathbb{R}$. Measures are objects which measure the size of subsets so you can think of these collections of subsets as collections of things we will measure.

These definitions are similar to the definition of a topology that you've hopefully seen before. In measure theory we are usually not able to work with any subset of our main set, we will have to restrict ourselves to a subcollection of all possible subsets and so we can think of these definitions as providing collections of sets which will be the objects we can measure.

We begin with the most basic definition. An algebra is is collection of sets closed under finite set operations. 

::: {.definition name="Algebra"}

A collection of subsets of a space $E$, $\mathcal{A}$, is called an algebra if

- $\emptyset \in \mathcal{A}, \, E \in \mathcal{A}$.
- If $A \in \mathcal{A}$ then $A^c \in \mathcal{A}$.
- If $A, B \in \mathcal{A}$ then $A \cup B \in \mathcal{A}$.
- If $A, B \in \mathcal{A}$ then $A \cap B \in \mathcal{A}$.

:::

We next define a $\sigma$-algebra. This is the *key* definition of a collection of sets for measure theory. The letter $\sigma$ here denotes countability. A $\sigma$-algebra is a collection of subsets of a space $E$, which are closed under countable set operations.

::: {.definition name="$\sigma$-algebra"}

A collection of subsets of a space $E$, $\mathcal{A}$ is a $\sigma$-algebra if

- $\emptyset \in \mathcal{A}, E \in \mathcal{A}$.
- If $A \in \mathcal{A}$ then $A^c \in \mathcal{A}$.
- If $A_1, A_2, \dots$ is a countable collection of sets in $\mathcal{A}$ then  $\bigcup_{n=1}^\infty A_n \in \mathcal{A}$.
- If $A_1, A_2, \dots$ is a countable collection of sets in $\mathcal{A}$ then $\bigcap_{n=1}^\infty A_n \in \mathcal{A}$.

:::

::: {.lemma}

We can equivalently define a $\sigma$-algebra as a collection of sets which contains $\emptyset$ and is closed under taking complements and countable unions.

We can think of this as a kind of *motto* for what a $\sigma$-algebra is.

:::

::: {.proof}

Suppose that $\mathcal{E}$ is closed under complements and taking countable unions and contains $\emptyset$, then it is clear that $E \in \mathcal{E}$. We need to show that if $(A_n)_n$ is a sequence in $\mathcal{E}$ then $\bigcap A_n \in \mathcal{E}$. We know that $\bigcap A_n = \left( \bigcup A_n^c \right)^c$ so this gives our result. 

:::


::: {.example}

In this course we really only deal with one concrete, non-trivial example of a $\sigma$-algebra. This is complicated to introduce and we will discuss below. 

However, in order to better understand the definition we give a few examples of things which are, and are not $\sigma$-algebras. 

- The main example is the Borel $\sigma$-algebra which we will meet in week 2
- The power set (set of all subsets) of $E$ is always a $\sigma$ algebra.
- If $A \subset E$ then $\{\emptyset, A, A^c, E\}$ is a $\sigma$-algebra.
- The set of all intervals in $\mathbb{R}$ is not a $\sigma$-algebra as it is not closed under taking unions.
- The set of all finite unions of half open intervals of the form$(a,b], a,b \in \mathbb{R}, (-\infty, b]$ or $(a, \infty), a \in \mathbb{R}\cup\{-\infty\}$ is an algebra but not a $\sigma$-algebra as it is closed under finite unions but not countable unions (work out why!).
- If  $A, B \neq \phi, E$ and $A \neq B, B^c$ then any $\sigma$-algebra containing $A$ and $B$ must contain $\phi, E, A, B, A^c, B^c, A\cup B, A\cap B, A^c \cup B^c, A^c \cap B^c, A^c \cup B, A^c \cap B, A \cup B^c, A \cap B^c, ((A \cap B) \cup (A^c \cap B^c)), ((A \cup B) \setminus (A \cap B))$. This is the smallest $\sigma$-algebra that contains $A$ and $B$.

:::

We now collect some results and further definitions about $\sigma$-algebras. The most important is the idea of a $\sigma$-algebra being generated by a smaller set.

::: {.lemma}

Suppose $E$ is a space and $\mathcal{C}$ is a collection of $\sigma$ algebras possibly uncountable. Then $\bigcap_{\mathcal{A} \in \mathcal{C}} \mathcal{A}$ is also a $\sigma$-algebra.

:::

::: {.proof}

It is straightforward to check that every part of the definition of a $\sigma$-algebra holds for the intersection. Just start writing down what the definition would mean.

:::

::: {.corollary}

For any collection of subsets of a space $E$, $\mathcal{F}$ there is a smallest $\sigma$-algebra containing $\mathcal{F}$. We call this $\sigma(\mathcal{F})$ or the $\sigma$-algebra generated by $\mathcal{F}$.

:::

::: {.proof}

There exists at least one $\sigma$-algebra containing $\mathcal{F}$ since the set of all subsets of $E$ is a $\sigma$ algebra. Then we can consider the non-empty intersection $\bigcap_{\mathcal{A} \in \mathcal{C}} \mathcal{A}$ where $\mathcal{C}$ is the collection of all $\sigma$-algebras which contain $\mathcal{F}$. We call this resulting $\sigma$- algebra the $\sigma$-*algebra generated by* $\mathcal{F}$.

:::

Let us now move on to one of the most important types of $\sigma$-algebra that we will consider. This is the *important* $\sigma$-algebra mentioned above.

:::{.example name="Key example: Borel $\sigma$-algebra"}

If $E$ is a topological space and $\mathcal{O}$ the family of open sets in $E$, then we write $\mathcal{B}(E)$ to be the $\sigma$-algebra generated by $\mathcal{O}$. This is called the Borel $\sigma$-algebra.

:::

We are most interested in $\mathcal{B}(\mathbb{R}^d)$. We have the following result

:::{.lemma}

$\mathcal{B}(\mathbb{R})$ is generated (recall this means the smallest $\sigma$-algebra containing this collection of subsets) by the following collections of subsets.

- The collection of closed sets in $\mathbb{R}$.
- The collection of intervals of the form $(-\infty, b]$.
- The collection of intervals of the form $(a,b]$.
- The collection of open intervals of the form $(a,b)$.

:::

:::{.proof}

Let us call $\mathcal{B}_1, \mathcal{B}_2, \mathcal{B}_3, \mathcal{B}_4$ to be the $\sigma$-algebras generated by the sets above. We then want to show that $\mathcal{B}(\mathbb{R}) \supseteq \mathcal{B}_1 \supseteq \mathcal{B}_2 \supseteq \mathcal{B}_3$. 

As $\mathcal{B}(\mathbb{R})$ contains all the open sets, it also contains all the closed sets (whose complements are open). Therefore, it also contains $\mathcal{B}_1$. 

As $\mathcal{B}_1$ contains all the closed sets, and all the intervals $(-\infty, b]$ are closed then $\mathcal{B}_1$ contains the $\sigma$-algebra generated by these sets, namely $\mathcal{B}_2$.

As $\mathcal{B}_2$ contains $(-\infty, b]$ and $(-\infty, a]$ and is closed under complements it also contains, $(-\infty, b]$ and $(a, \infty)$. As $\mathcal{B}_2$ is closed under intersection, this means it also contains $(a,b]$. This is true for all $a<b$ so $\mathcal{B}_2$ contains all sets of this form. Consequently, it contains $\mathcal{B}_3$.

Now we can see that $\mathcal{B}_3$ contains $\bigcup_n (a,b-1/n] = (a,b)$ for every $(a,b)$ therefore $\mathcal{B}_3$ contains $\mathcal{B}_4$.

Now we want to show that $\mathcal{B}(\mathbb{R}) \subseteq \mathcal{B}_4$. This will conclude the proof. We need to show that any open set in $\mathbb{R}$ is a countable union of open intervals. Let $U$ be such an open set then let 
\[ O = \bigcup_{q \in \mathbb{Q} \cap U} \bigcup_{r \in \mathbb{Q} \, \mbox{s.t} \, (q-r,q+r) \subseteq U} (q-r,q+r). \] Then since $O$ is a union of subsets of $U$ then $O \subseteq U$. Suppose that $x \in U$ then there exists some $\rho$ such that $(x-\rho, x+\rho) \subseteq U$. There are some rationals $q,r$ such that $x \in (q-r,q+r) \subseteq (x-\rho,x+\rho)$ therefore $x \in O$. Consequently $U= O$. 

:::

::: {.remark}

It is worth noting that $\mathcal{B}(\mathbb{R})$ is very big and contains many more sets than just open sets and closed sets. It is in fact very difficult to come up with a set which isn't a Borel set. We can think of all the sets in the Borel $\sigma$-algebra in a hierarhcy: open sets, countable intersections of open sets, countable unions of countable intersections of open sets, countable intersections of countable unions of open sets ... and so on. It is never the case that you can't generate more new sets by finding countable intersection or countable unions of sets from the previous set in the hierarchy. 

:::


We have two further definitions of collections of sets which will be useful. These separate the two parts of the definition of a $\sigma$-algebra.

Rather than thinking of these as a collection of subsets that we can measure or pay attention to these definitions will typically appear inside proofs.

::: {.definition name="$\pi$-system"}

A collection of subsets of $E$, $\mathcal{A}$ is a $\pi$-system if

- $\emptyset \in \mathcal{A}$
- If $A, B \in \mathcal{A}$ then $A \cap B \in \mathcal{A}$.

:::

::: {.definition name="$D$-system"}

A collection of subsets of $E, \mathcal{A}$ is a $d$-system if

- $E \in \mathcal{A}$.
- If $A, B \in \mathcal{A}$ with $A \subset B$ then $B \setminus A \in \mathcal{A}$.
- If $A_1 \subset A_2 \subset A_3 \subset \dots$ then $\bigcup_{n=1}^\infty A_n \in \mathcal{A}$.

:::

::: {.lemma name="Dynkin's $\pi$-system lemma"}

Let $\mathcal{A}$ be a $\pi$-system. Then any $d$-system containing $\mathcal{A}$ also contains the $\sigma$-algebra generated by $\mathcal{A}$.
:::

::: {.proof} 

This is an exercise.

:::

## Set functions

We are now able to introduce the next important set of objects we will be studying in the course. These are measures. We can think of these as measuring the size of different sets.

::: {.definition name="Set function"}

A set function $\phi$ is a function from a family of subsets of a space $E$, $\mathcal{A}$ to $\mathbb{R}\cup\{\infty\}$.

:::

::: {.definition name="Measure"}

A measure is a specific type of set function which satisfies certain axioms. A set function $\mu$ defined from a $\sigma$-algebra $\mathcal{A}$ is a measure if,

- $\mu(A) \geq 0$ for every $A \in \mathcal{A}$.
- $\mu(\emptyset) = 0$
- If $A_1, A_2, A_3, \dots$ are all pairwise disjoint and in $\mathcal{A}$ then 

$$\mu \left( \bigcup_n A_n \right) = \sum_n \mu(A_n).$$

We call this last property *countable additivity*. Note that the domain of a measure *must be* a $\sigma$-algebra.
:::

::: {.example name="Delta (function)"}

You've probably seen $\delta_{x_0}(x)$ used before; it is similar to the Kroeneker delta which appears in discrete spaces $\delta_{x,y} = 1$ if and only if $x=y$. This is the `function' defined by $\int \delta_{x_0}(x)f(x) \mathrm{d}x = f(x_0)$.  We can define a measure on $\mathbb{R}^d$ which will have this property by 

$$\delta_{x_0}(A) = \left\{ \begin{array}{ll} 1 & x_0 \in A \\ 0 & x_0 \notin A \end{array} \right.$$

:::

::: {.example name="Countable spaces"}
If $E = \{ x_1, x_2, \dots\}$ is a countable space and $F: E \rightarrow \mathbb{R}_{\geq 0}$ is a non-negative function then we can define a measure by $\mu(A) = \sum_n F(x_n)1_{x_n \in A}$. In fact any measure on a countable set can be written this way by choosing $F(x_n) = \mu(\{x_n\})$.

:::

::: {.example name="Function (informally)"}

In the course we will define this rigorously later. However we can define a measure on $\mathbb{R}^d$ by integrating a function over subsets of $\mathbb{R}^d$. If $f$ is a non-negative function then we define $\mu_f(A) = \int_A f(x) \mathrm{d}x$.

:::

We also define two further possible properties of set functions

::: {.definition name="monotonicity"
}
A set function $\phi$ is monotone if whenever $A \subseteq B$ we have $\phi(A) \leq \phi(B)$.

:::

::: {.definition name="Countable subadditivity"}

A set function $\phi$ is countably subadditive if for every sequence of sets $A_1, A_2, A_3, \dots$ we have 

$$ \phi \left( \bigcup_n A_n \right) \leq \sum_n \phi(A_n). $$

:::

::: {.lemma}

If $\mu$ is a measure the $\mu$ is both monotone and countably subadditive.

:::

::: {.proof}
Suppose $A \subseteq B$ then $B = A \cup (B \setminus A)$ and this union is disjoint. Countable additivity then implies that $\mu(B) = \mu(A) + \mu(B \setminus A)$ and since $\mu(B \setminus A) \geq 0$ we have $\mu(A) \leq \mu(B)$.

Now take a sequence $A_1, A_2, A_3, \dots$ and define $B_n = A_n \setminus \left(A_n \cap \bigcup_{k=1}^{n-1}A_k \right)$ then the $B_n$ form a disjoint sequence with $\bigcup_n A_n = \bigcup_n B_n$. We also have, for every $n$, that $B_n \subseteq A_n$ so by monotonicity $\mu(B_n) \leq \mu(A_n)$. Then using countable additivity on the union of the $B_n$ we have
\[ \mu(\bigcup_n A_n) = \mu(\bigcup_n B_n) = \sum_n \mu(B_n) \leq \sum_n \mu(A_n). \]

:::

## Measure spaces

We have seen that in order to define a measure you need to start with a $\sigma$-algebra. Normally we consider the base space, $\sigma$-algebra, and measure all coming together. This forms the fundamental object we study in the first half of the course. You can compare the idea of a measure space to that of a topological space.

::: {.definition name="Measurable space"}

We call a pair $(E, \mathcal{A})$ of a space and a $\sigma$-algebra, a *measureable space*.

:::

::: {.definition name="Measure space"}

We call a triple $(E, \mathcal{A}, \mu)$ of a space, a $\sigma$-algebra and a measure a *measure space*.

:::

::: {.definition name="Finite measure space"}

We call a measure space $(E, \mathcal{A}, \mu)$ *finite* if $\mu(E) < \infty$.

:::

Again we have some further definitions for specific properties measure spaces can have. You can explore these definitions a bit more with the exercises. 

::: {.definition name="$\sigma$-finite measure space"}

We call a measure space, $(E, \mathcal{A}, \mu)$, $\sigma$-*finite* if there exists a countable collection $E_1, E_2, \dots \in \mathcal{A}$ such that
$$ E = \bigcup_n E_n, $$ 
and

$$ \mu(E_i) < \infty, \, \forall i. $$

:::

::: {.definition name="Borel measures and Radon measures"}
A measure $\mu$ on a subset of a topological space $E$ is called a *Borel measure* if it is a measure with respect to the Borel $\sigma$-algebra.

A Borel measure is called a *Radon measure* if for every compact set $K \in \mathcal{B}(E)$ we have that $\mu(K) < \infty$.

:::

We can now prove the first theorem in our course. This is known as continuity of measure and it shows that we can approximate the measure of a set by finding a sequence of sets that approach that set.

::: {.theorem name="Continuity of measure"}

Let $(E, \mathcal{E}, \mu)$ be a measure space. Suppose that $(A_n)_n$ is a sequence of measurable sets with $A_1 \subseteq A_2 \subseteq \dots$ and $(B_n)_n$ is a sequence of measurable sets with $B_1 \supseteq B_2 \supseteq \dots$, and $\mu(B_1)< \infty$ then we have

$$ \mu\left( \bigcup_n A_n\right) = \lim_n \mu(A_n) $$
and 

$$ \mu\left( \bigcap_n B_n \right) = \lim_n \mu(B_n). $$

:::

::: {.proof}

Let $\tilde{A}_n = A_n \setminus A_{n-1}$. We have that $\bigcup_n A_n = \bigcup_n \tilde{A}_n$. Furthermore, countable additivity gives us that
\[ \mu\left( \bigcup_n \tilde{A}_n \right) = \sum_n \mu(\tilde{A}_n). \] Therefore, we have $\sum_{n=1}^m \mu(\tilde{A}_n) \rightarrow \mu \left( \bigcup_n A_n \right)$. We also have $\sum_{n=1}^m \mu(\tilde{A}_n) = \mu \left( \bigcup_{n=1}^m \tilde{A}_n \right) = \mu (A_m)$.

Now we move onto the $B_n$, let $C_n = B_1 \setminus B_n$ then the $C_n$ are an increasing sequence of measurable sets with $C_n \uparrow B_1 \setminus \bigcap_n B_n$. So by the first part we have $\mu\left(B_1 \setminus \bigcap_n B_n \right) = \lim_n \mu(C_n)$. Therefore
\[ \mu(B_1) - \mu\left( \bigcap_n B_n \right) = \mu(B_1) - \lim_n \mu(B_n). \] This gives the result as long as $\mu(B_1) < \infty$. If there exist an $m$ such that $\mu(B_m) < \infty$ then we can renumber starting with $m$ and repeat the argument above. 

N.b. the fact that $\mu(B)< \infty$ implies $\mu(A)< \infty$ if $B \subset A$ follows from finite additivity. $\mu(B) = \mu(A) + \mu(B \setminus A) \geq \mu(A)$.

:::