# Outer measures and Lebesgue Measure

In this section we will define Lebesgue measure which is one of the most fundamental objects in this course. Lebesgue measure is the measure which generalises the notion of length/area/volume to sets where we don't have an existing idea of their length/area/volume.

In order to do this we first define something called Lebesgue outer measure. So we start by finding out what an outer measure is.

::: {.definition name="Outer measure"}

We write $\mathscr{P}(E)$ to be the power set of $E$, that is to say the set of all subsets of $E$. An outer measure is a function, $\nu$, from $\mathscr{P}(E) \rightarrow \mathbb{R}_+ \cup \{\infty\}$ such that

- $\nu(\emptyset) =0$,
- If $A \subseteq B$ then $\nu (A) \leq \nu(B)$, (this is called *monotonicity*)
- If $A_1, A_2, \dots$ is a sequence of subsets then $\nu\left( \bigcup_n A_n \right) \leq \sum_n \nu(A_n)$, (this is called *countable subadditivity*).

:::

The key example of an outer measure is *Lebesgue outer measure*, defining this is our first step to defining Lebesgue measure. 

WARNING: Throughout this section $\lambda$ is going to be redefined a few times. Eventually it will be Lebesgue measure. I'll only call something $\lambda$ if it is consistent with Lebesgue measure and defined on a smaller collection of sets that $\mathcal{B}(\mathbb{R})$.

::: {.definition name="Lebesgue measure on intervals"}

Let us write $\mathcal{I}$ to be the set of half open intervals. Then we define a set function $\lambda$ from $\mathcal{I}$ to $\mathbb{R}$ by

$$ \lambda \left( (a,b] \right) = b-a.$$

:::


Using this we can define Lebesgue outer measure.

::: {.definition name="Lebesgue outer measure"}

We define Lebesgue outer measure on $\mathscr{P}(\mathbb{R})$ by 

$$\lambda^* (A) = \inf \{ \sum_n\lambda (I_n) \, : \, \mbox{$I_n$ are half open intervals}\, , A \subset \bigcup_n I_n\}. $$

:::

::: {.proposition}

Lebesgue outer measure is an outer measure and agrees with $\lambda$ on any half open interval.

:::

::: {.proof}

We need to check each part of the definition of outer measure. First the fact that $\lambda^*(\emptyset) = 0$ follows from the fact that $\emptyset \in \mathcal{I}$ and $\lambda(\emptyset) = 0$. Now suppose that $A_1 \subset A_2$, then any set $B$ which is a countable union of half open intervals with $A_2 \subseteq B$ also has $A_1 \subseteq B$ so

$$ \inf \{ \sum_n\lambda (I_n) \, : \, \mbox{$I_n$ are intervals}\,, A_1 \subset B = \bigcup_n I_n\} \leq \inf \{ \sum_n\lambda (I_n) \, : \, \mbox{$I_n$ are intervals}\,, A_2 \subset B = \bigcup_n I_n\}, $$

as the infimum over a larger set will always be smaller. Now let us turn to the countable subadditivity. Let us take some sequence $A_1, A_2, \dots$, if $\sum_n \lambda^*(A_n) = \infty$ then we are done. Therefore we can assume that $\sum_n \lambda^*(A_n) < \infty$. Now let us fix an arbitrary $\epsilon>0$. Now by the definition of $\lambda^*$ for each $n$ there exists some $B_n$ such that $A_n \subseteq B_n$ and $B_n = \bigcup_k I_{n,k}$ where the $I_{n,k}$ are half open intervals, and $\sum_k\lambda(I_{n,k}) \leq \lambda^* (A_n) + \epsilon 2^{-n}$. Then the set $I = \bigcup_n B_n$ is a countable union of half open intervals and $\sum_{n,k}\lambda(I_{n,k}) = \sum_n \sum_k\lambda(I_{n,k}) \leq \sum_n \lambda^*(A_n) + \epsilon$. Therefore $\lambda^*(\bigcup_n A_n) \leq  \sum_n \lambda^*(A_n) + \epsilon$.

Lastly if $A$ is the interval $(a,b]$ then $(a,b] \in \mathcal{I}$ so $\lambda^*(A) \leq b-a$. 

 Suppose that $(a,b] \subseteq (c_1,d_1] \cup (c_2, d_2] \cup \dots$.  Then we have that for any $\epsilon, \delta$ that 

$$ [a+\epsilon, b-\epsilon] \subseteq (c_1-\delta/2, d_1 + \delta/2) \cup (c_2 - \delta/4, d_2 + \delta/4) \cup \dots (c_k -2^{-k} \delta, d_k + 2^{-k} \delta) \cup \dots.  $$

Then using compactness (which tells us any open cover of a compact set has a finite subcover) there exists some $n$ such that

$$ [a+\epsilon, b-\epsilon] \subseteq \bigcup_{k=1}^n (c_k -2^{-k}\delta, d_k + 2^{-k} \delta). $$

Now we know about the lengths of finite unions of intervals (Lebesgue measure doesn't wipe out our existing knowledge of length) so we can compare the lengths of the sides to get

$$ b-a - 2\epsilon \leq \sum_{k=1}^n (d_k - c_k + 2^{-k+1} \delta) \leq \sum_{k=1}^\infty (d_k-c_k) + 2 \delta. $$ 

Both $\epsilon$ and $\delta$ are arbitrary so we can let them go to $0$ and get

$$ b-a \leq \sum_k (d_k - c_k). $$

Now ranging over all possible covering sequences gives

$$ b-a \leq \lambda^*((a,b]). $$

Note: When we are working in $\mathbb{R}^d$ as in the assignment the terms involving $\epsilon$ and $\delta$ will be multiplied by something involving the side lengths of rectangles. In order to run the proof you can say that wlog all the rectangles you are looking at are contained inside some fixed large rectangle. This will allow you to send $\epsilon$ and $\delta$ to zero without having to worry.

:::


We want to turn this outer measure into a true measure. In order to do this we need to restrict $\lambda^*$ to some subset of $\mathscr{P}(\mathbb{R})$.

::: {.definition name="Lebesgue Measurable sets"}

We call a set $A \in \mathscr{P}(\mathbb{R})$ is *Lebesgue Measureable* if for any $B \in \mathscr{P}(\mathbb{R})$ we have 

$$ \lambda^*(B) = \lambda^*(A \cap B) + \lambda^*(A^c \cap B). $$
:::

::: {.proposition}

The collection of Lebesgue measureable sets, $\mathscr{M}$, is an algebra.

:::

::: {.proof}

First let us notice that the definition of a Lebesgue measureable sets is symmetric in $A$ and $A^c$, so $A \in \mathscr{M}$ implies that $A^c \in \mathscr{M}$.

Secondly we can see that $\emptyset \in \mathscr{M}$ as $\lambda^*(A\cap \emptyset) + \lambda^*(A \cap \emptyset^c) = \lambda^*(\emptyset) + \lambda^*(A \cap E) = 0+ \lambda^*(A)$. This also implies via the first point that $E \in \mathscr{M}$.

We then show that if $A_1, A_2 \in \mathscr{M}$ then $A_1 \cup A_2 \in \mathscr{M}$. Using the fact that $A_1 \in \mathscr{M}$ we have

\begin{align*} \lambda^*(B \cap (A_1 \cup A_2)) &= \lambda^*(B \cap (A_1 \cup A_2) \cap A_1) + \lambda^*(B \cap(A_1 \cup A_2) \cap A_1^c)\\
&= \lambda^* (B \cap A_1)  + \lambda^* (B \cap A_2 \cap A_1^c).  
\end{align*}
We also have the identity $(A_1 \cup A_2)^c = A_1^c \cap A_2^c$ therefore

$$ \lambda^*(B \cap (A_1 \cup A_2)) + \lambda^*(B \cap (A_1 \cup A_2)^c) = \lambda^*(B \cap A_1) + \lambda^* (B \cap A_2 \cap A_1^c) + \lambda^*(B \cap A_1^c \cap A_2^c). $$
Then since $A_2 \in \mathscr{M}$ we have

$$  \lambda^* (B \cap A_2 \cap A_1^c) + \lambda^*(B \cap A_1^c \cap A_2^c) = \lambda^*(B \cap A_1^c).$$

Therefore,

$$  \lambda^*(B \cap (A_1 \cup A_2)) + \lambda^*(B \cap (A_1 \cup A_2)^c) = \lambda^*(B \cap A_1) + \lambda^*(B \cap A_1^c). $$
Then we use again the fact that $A_1 \in \mathscr{M}$ to get

$$  \lambda^*(B \cap (A_1 \cup A_2)) + \lambda^*(B \cap (A_1 \cup A_2)^c) =\lambda^*(B). $$

This shows that $A_1 \cup A_2 \in \mathscr{M}$. 

:::



::: {.proposition}

$\mathscr{M}$ is a $\sigma$-algebra and the restriction of $\lambda^*$ to $\mathscr{M}$ is a measure. 

:::

::: {.proof}

Let us take an infinite sequence of disjoint sets $A_1, A_2, A_3, \dots$ then we will show 

$$ \lambda^*(B) = \sum_{i=1}^n \lambda^* (B \cap A_i) + \lambda^*\left( B \cap \left( \bigcap_{i=1}^n A_i^c \right) \right). $$

We can show this by induction. For the base case it just follows with $n=1$ from the fact that $A_1 \in \mathscr{M}$. Then by induction suppose we know that

$$ \lambda^*(B) = \sum_{i=1}^{n-1} \lambda^*(B \cap A_i) + \lambda^*\left( B \cap \left( \bigcap_{i=1}^{n-1} A_i^c \right) \right).  $$

Now since $A_n \in \mathscr{M}$ we have

$$ \lambda^*\left( B \cap \left( \bigcap_{i=1}^{n-1} A_i^c \right) \right) = \lambda^* \left(B \cap A_n \cap \left( \bigcap_{i=1}^{n-1} A_i^c \right)  \right) + \lambda^* \left( B \cap A_n^c \cap \left( \bigcap_{i=1}^{n-1} A_i^c \right) \right).$$

Now since $A_n$ is disjoint from $A_1, \dots, A_{n-1}$ we have that $A_n \cap \left( \bigcap_{i=1}^{n-1} A_i^c \right)  = A_n$ so we have 
$$  \lambda^*\left( B \cap \left( \bigcap_{i=1}^{n-1} A_i^c \right) \right) = \lambda^*(B \cap A_n) + \lambda^*\left( B \cap \left( \bigcap_{i=1}^{n} A_i^c \right) \right). $$

This gives our induction step. 

By monotonicity of the outer measure this gives that for any $n$ we have

$$ \lambda^*(B) \geq \sum_{i=1}^n \lambda^*(B \cap A_i) + \lambda^* \left(B \cap \left( \bigcap_{i=1}^\infty A_i^c \right) \right). $$
Consequently we can let $n$ tend to infinity to get

$$ \lambda^*(B) \geq \sum_{i=1}^\infty \lambda^*(B \cap A_i) +\lambda^* \left(B \cap \left( \bigcap_{i=1}^\infty A_i^c \right) \right). $$
Now we can use the countable subadditivity of $\lambda^*$ to get

$$ \lambda^*(B) \geq \lambda^*\left( B \cap \left( \bigcup_{i=1}^\infty A_i \right)\right) + \lambda^*\left((B \cap \left( \bigcap_{i=1}^\infty A_i^c \right) \right) = \lambda^* \left( B \cap \left( \bigcup_{i=1}^\infty A_i \right) \right) + \lambda^* \left( B \cap \left( \bigcup_{i=1}^\infty A_i \right)^c \right).$$

Furthermore, the subadditivity of $\lambda^*$ gives

$$ \lambda^*(B) \leq  \lambda^* \left( B \cap \left( \bigcup_{i=1}^\infty A_i \right) \right) + \lambda^* \left( B \cap \left( \bigcup_{i=1}^\infty A_i \right)^c \right). $$

Therefore, 

$$ \lambda^*(B) =  \lambda^* \left( B \cap \left( \bigcup_{i=1}^\infty A_i \right) \right) + \lambda^* \left( B \cap \left( \bigcup_{i=1}^\infty A_i \right)^c \right). $$

This shows that if $(A_n)_{n \geq 1}$ is a sequence of *disjoint* sets in $\mathscr{M}$ then $\bigcup_n A_n \in \mathscr{M}$. 

Now take a $\tilde{A}_n$ sequence of sets in $\mathscr{M}$ which aren't necessarily disjoint. Then define $A_n = \tilde{A}_n \setminus \left( \tilde{A}_n \cap \bigcup_{k=1}^{n-1} \tilde{A}_k\right)$ then $\bigcup_n A_n = \bigcup_n \tilde{A}_n$ and the $A_n$s are defined to be disjoint. Furthermore, $A_n \in \mathscr{M}$ because it can be made from the $\tilde{A}_n$ by finitely many set operations and we showed that $\mathscr{M}$ is an algebra. Now as all the $A_n$ are disjoint and in $\mathscr{M}$ this shows $\bigcup_n A_n \in \mathscr{M}$. This shows that $\mathscr{M}$ is closed under countable unions so is a $\sigma$-algebra.


We need to show that $\lambda^*$ is countably additive on $\mathscr{M}$ so let $A_1, A_2, \dots$ be a sequence of disjoint subsets in $\mathscr{M}$. In the proof that $\mathscr{M}$ is a $\sigma$-algebra we showed that 

$$ \lambda^*(B) \geq \sum_{i=1}^\infty \lambda^*(B \cap A_i) + \lambda^* \left( B \cap \left( \bigcap_{i=1}^\infty A_i^c \right) \right). $$
Now let us take the particular case where $B = \bigcup_{i=1}^\infty A_i$ this gives

$$ \lambda^* \left( \bigcup_{i=1}^\infty A_i \right) \geq \sum_{i=1}^n \lambda^*(A_i) + \lambda^* \left(\left( \bigcup_{i=1}^\infty A_i \right) \cap \left( \bigcup_{i=1}^\infty A_i \right)^c \right) = \sum_{i=1}^\infty \lambda^* (A_i). $$
Countable subadditivity gives

$$ \lambda^* \left( \bigcup_{i=1}^\infty A_i \right) \leq \sum_{i=1}^n \lambda^*(A_i),  $$

so consequently

$$ \lambda^* \left( \bigcup_{i=1}^\infty A_i \right) = \sum_{i=1}^n \lambda^*(A_i).  $$

:::

::: {.remark}

We now call the restriction of $\lambda^*$ to $\mathscr{M}$, $\lambda$ and call it *Lebesgue measure*.

:::

We now want to know that there are some Lebesgue measurable sets. In order to do this we first show that all the intervals of the form $(-\infty, b]$ are Lebesgue measurable.

::: {.lemma}

The intervals of the form $(-\infty, b]$ are Lebesgue measureable.

:::

::: {.proof}

Let $B$ be a subset of $\mathbb{R}$ and let $I_1, I_2, \dots$ be a sequence of half open intervals such that $B \subseteq I_1 \cup I_2 \cup \dots$. Now let us define the (often empty) intervals $I^l_i = I_i \cap (-\infty, b]$ and $I^r_i = I_i \cap (b, \infty)$, these are also half open intervals. We have $B \cap (-\infty,b] \subseteq \bigcup_n I^l_n$ and $B \cap (b,\infty) \subseteq \bigcup_n I^r_n$. Therefore we have

$$ \lambda^*(B \cap (-\infty, b]) \leq \sum_n \lambda(I^l_n), \quad \lambda^*(B \cap (b,\infty)) \leq \sum_n \lambda(I^r_n). $$

Using this we have

$$ \lambda^*(B \cap(-\infty,b])) + \lambda^*(B \cap (b,\infty)) \leq \sum_n \lambda(I^l_n) + \sum_n \lambda(I^r_n) = \sum_n \lambda(I_n).$$
We can then take the infimum over all possible sequences of intervals covering $B$ to get

$$ \lambda^*(B \cap(-\infty,b])) + \lambda^*(B \cap (b,\infty)) \leq \lambda^*(B). $$

Combining this with countable subadditivity gives

$$ \lambda^*(B) = \lambda^*(B \cap(-\infty,b])) + \lambda^*(B \cap (b,\infty)). $$

Therefore, $(-\infty,b]$ is Lebesgue measurable.

:::

::: {.corollary}

Every set in $\mathcal{B}(\mathbb{R})$ is Lebesgue measurable.

:::

::: {.proof}

The Borel $\sigma$ algebra is the $\sigma$ algebra generated by sets of the form $(-\infty, b]$ as shown last week. Therefore, as $\mathscr{M}$ is a $\sigma$-algebra and contains all the intervals of the form $(-\infty, b]$ then it contains the Borel $\sigma$-algebra.

:::





The construction of Lebesgue measure via the outer measure can be generalised via Carathéodory's extension theorem. This theorem is not examinable and won't be lectured. The main objective here is to go over the ideas in the proof of the construction of Lebesgue measure again. Hopefully seeing things in a more abstract form helps draw out the key ideas.

We briefly give the defintion of a ring of subsets. This is different (though a bit similar) to the definition you may have seen in group theory.

::: {.definition name="Ring"}

A collection of subsets, $\mathcal{A}$, of a space $E$ is called a ring if for every $A,B \in \mathcal{A}$ we have $A \setminus B \in \mathcal{A}$ and $A \cup B \in \mathcal{A}$.

:::

Now we introduce Carathéodory's Extension theorem. We can see that the proof is in many ways very similar to the construction of Lebesgue measure. 


::: {.theorem name="Carathéodory's Extension Theorem"}

Let $\mathcal{A}$ be a ring of subsets of $E$, and let $\mu: \mathcal{A} \rightarrow [0, \infty]$ be a countably additive set function. Then $\mu$ extends to a measure on $\sigma(\mathcal{A})$.

:::

::: {.proof}

We define the outer measure $\mu^*$ on $\mathscr{P}(E)$ by

$$ \mu^*(B) = \inf \left\{ \sum_n \mu(A_n) \,:\, A_n \in \mathcal{A} \forall n, B \subset \bigcup_n A_n \right\}.$$
We have that $\mu^*(B) = \infty$ if there is not possible sequence of $A_n$ so that $B$ is contained in their union. We can see immediately that $\mu^*(\emptyset) =0$ and $\mu^*$ is increasing. 

As before we define $\mathscr{M}$ to be the set of $\mu^*$ measurable sets $A$ that satisfy, for every $B \subseteq E$ that

$$ \mu^*(B) = \mu^*(B \cap A) + \mu^*(B \cap A^c).  $$
We want to show that $\mathscr{M}$ is a $\sigma$-algebra and that $\mu^*$ restricts to a measure on $\mathscr{M}$.

First we show that $\mu^*$ is countably subadditive. Suppose that we have a sequence $B_n$ and want to show that

$$ \mu^*\left( \bigcup_n B_n\right) \leq \sum_n \mu^*(B_n). $$

Let us fix some $\epsilon >0$ then for each $n$ there is a sequence $A_{n,m} \in \mathcal{A}$ such that $B_n \subset \bigcup_m A_{n,m}$ and $\sum_m \mu(A_{n,m}) \leq \mu^*(B_n) + \epsilon 2^{-n}$. Then $\bigcup_n B_n \subset \bigcup_{n,m} A_{n,m}$ and $\sum_{n,m}\mu(A_{n,m}) \leq \sum_n \mu^*(B_n) + \epsilon$. Therefore $\mu^* \left( \bigcup_n B_n \right) \leq \sum_n \mu(B_n) + \epsilon$. Since $\epsilon$ is arbitrary this gives the countable subadditivity. 

Now we show that $\mu^*$ agrees with $\mu$ on $\mathcal{A}$. Let us take $A \in \mathcal{A}$ clearly $A \subseteq A$ so $\mu^*(A) \leq \mu(A)$. Now suppose that there is a sequence $A_n \in \mathcal{A}$ such that $A \subseteq \bigcup_n A_n$. Then $A \cap A_n = A \setminus (A \setminus A_n) \in \mathcal{A}$. Therefore we use the countable subadditivity of $\mu$ on $\mathcal{A}$ to get

$$ \mu (A) \leq  \sum_n \mu(A_n \cap A) \leq \sum_n \mu(A_n).$$

Taking the infimum over such sequences gives $\mu(A) \leq \mu^*(A)$. Therefore $\mu$ and $\mu^*$ agree on $\mathcal{A}$. 

Now we show that $\mathscr{M}$ contains $\mathcal{A}$. That is to say we want to show that if $A \in \mathcal{A}$ then for every $B$

$$ \mu^*(B) = \mu^*(B \cap A) + \mu^*(B \cap A^c). $$
Using subadditivity of $\mu^*$ we have that $\mu^*(B) \leq \mu^*(B \cap A) + \mu^*(B \cap A^c)$. Therefore we want to show $\mu^*(B) \geq \mu^*(B \cap A) + \mu^*(B \cap A^c)$. Let $A_n$ be a sequence in $\mathcal{A}$ such that $\mu^*(B) \geq \sum_n \mu(A_n) - \epsilon, B \subseteq \bigcup_n A_n$, then we already know that $A \cap A_n$ will be in $\mathcal{A}$ we also have that $A^c \cap A_n = A_n \setminus (A \cap A_n) \in \mathcal{A}$. Therefore $\mu(B \cap A) \leq \sum_n \mu(A_n \cap A)$ and $\mu(B \cap A^c) \leq \sum_n \mu(A^c \cap A_n)$ and consequently

$$ \mu^*(B \cap A) + \mu^*(B \cap A^c) \leq \sum_n \left( \mu(A_n \cap A) + \mu(A_n \cap A^c) \right) = \sum_n \mu(A_n) \leq \mu^*(B) + \epsilon. $$
As $\epsilon$ is arbitrary this gives the required result. 

The next step is to show that $\mathscr{M}$ is a $\sigma$-algebra. We start with the algebra part. $E$ and $\emptyset$ are in $\mathscr{M}$ as

$$ \mu^*(B) = \mu^*(B \cap E) + \mu^*(B \cap \emptyset), $$

 just because $B \cap E = B$ and $B \cap \emptyset = \emptyset$ and we know $\mu^*(\emptyset) =0$. We also can see that
 
$$ \mu^*(B) = \mu^*(B \cap A) + \mu^*(B \cap A^c) $$

is symmetric in exchanging $A$ and $A^c$ so if $A \in \mathscr{M}$ then so is $A^c$. Now suppose $A_1, A_2 \in \mathscr{M}$. We notice that $(A_1 \cap A_2)^c \cap A_1 = (A_1^c \cup A_2^c) \cap A_1 = (A_1^c \cap A_1) \cup (A_2^c \cap A_1) = A_2^c \cap A^1$ and $A_1^c = A_1^c \cap(A_1 \cap A_2)^c$. Using this and the fact that $A_1, A_2, A_1^c, A_2^c$ are in $\mathscr{M}$ we have

\begin{align*}\mbox{Using that} \, A_1 \in \mathscr{M} \quad \mu^*(B) &= \mu^*(B \cap A_1) + \mu^*(B \cap A_1^c)\\
\mbox{Using that}\, A_2 \in \mathscr{M} \quad &= \mu^*(B \cap (A_1 \cap A_2)) + \mu^*(B \cap A_1 \cap A_2^c) + \mu^*(B \cap A_1^c)\\
\mbox{Using our first identity} \quad &= \mu^*(B \cap (A_1 \cap A_2)) + \mu^*(B \cap (A_1 \cap A_2)^c \cap A_1) + \mu^*(B \cap A_1^c)\\
\mbox{Using our second identiy} \quad &= \mu^*(B \cap (A_1 \cap A_2)) + \mu^*(B \cap (A_1 \cap A_2)^c \cap A_1) + \mu^*(B \cap (A_1 \cap A_2)^c \cap A_1^c)\\
\mbox{Using the fact that}\, A_1 \in \mathscr{M} \quad &= \mu^*(B \cap (A_1 \cap A_2)) + \mu^*(B \cap (A_1 \cap A_2)^c).
\end{align*}

Now that we have shown that $\mathscr{M}$ contains finite unions we want to show it countains countable unions. Let $A_n$ be a sequence of disjoin sets in $\mathscr{M}$. Let us write $A = \bigcup_n A_n$. Then itterating our previous result we have for any $B, n$ that

$$ \mu^*(B) = \sum_{k=1}^n \mu^*(B \cap A_k) + \mu^*( B \cap A_1^c \cap \dots \cap A_n^c). $$

Now as $A^c \subseteq A_1^c \cap A_2^c \dots \cap A_n^c$ for each $n$ we have $\mu^*(B \cap A^c) \leq \mu^*(B \cap A_1^c \cap \dots \cap A_n^c)$. Therefore for each $n$

$$ \mu^*(B) \geq \sum_{k=1}^n \mu^*(B \cap A_k) + \mu^*(B \cap A^c). $$

Letting $n \rightarrow \infty$ we have

$$ \mu^*(B) \geq \sum_n \mu^*(B \cap A_n) + \mu^*(B \cap A^c). $$

Now we use the countable subadditivity of $\mu^*$ and the fact that $B \cap A = \bigcup_n (B \cap A_n)$ to get

$$ \mu^*(B) \geq \mu^*(B \cap A) + \mu^*(B \cap A^c). $$

As the other inequality holds by subadditivity of $\mu^*$ we have that $\mu^*(B) = \mu^*(B \cap A) + \mu^*(B \cap A^c)$ and hence $A \in \mathscr{M}$.

Lastly, we want to show that $\mu^*$ is a measure on $\mathscr{M}$. In order to do this we need to show that $\mu^*$ is countably additive on $\mathscr{M}$. In the last step we showed that for any $B$, and a sequence of disjoint sets $A_n$ in $\mathscr{M}$ with $A= \bigcup_n A_n$, that

$$ \mu^*(B) \geq \sum_n \mu^*(A_n \cap B) + \mu^*(B \cap A^c). $$

If we apply this identity with $B=A$ and use the fact that $A_n \cap A = A_n$ we get

$$ \mu^*(A) \geq \sum_n \mu^*(A_n). $$

Since we already know that $\mu^*$ is countably subadditive this is sufficient to show that $\mu^*$ is countably additive and hence a measure on $\mathscr{M}$.

:::

::: {.theorem name="Uniqueness of Extension"}

Let $\mu_1$ and $\mu_2$ be measures on $(E,\mathcal{E})$ with $\mu_1(E) = \mu_2(E) < \infty$. Suppose that $\mu_1 = \mu_2$ on $\mathcal{A}$ where $\mathcal{A}$ is a $\pi$-system generating $\mathcal{E}$, then $\mu_1 = \mu_2$ on $\mathcal{E}$.

:::

::: {.proof}

Let us consider $\mathcal{D} \subseteq \mathcal{E}$ defined as the measurable sets on which $\mu_1(A) = \mu_2(A)$. By hypothesis $E \in \mathcal{D}$ and $\mathcal{A} \subseteq \mathcal{D}$. We want to show that $\mathcal{D}$ is a $\sigma$-algebra and therefore $\mathcal{D} = \mathcal{E}$. Suppose that $A, B \in \mathcal{E}$ with $A \subseteq B$ then we have $\mu_i(A) + \mu_i (B \setminus A) = \mu_i(B) < \infty.$ This means that if $A$ and $B$ are in $\mathcal{D}$ then so is $A \setminus B$.  Suppose that $A_n$ is a sequence of elements in $\mathcal{D}$ with $A_1 \subseteq A_2 \subseteq A_3 \dots$ then by continuity of measure $\mu_1(\bigcup_n A_n) = \lim_n \mu_1(A_n) = \lim_n \mu_2(A_n) = \mu_2(\bigcup_n A_n)$. Therefore $\bigcup_n A_n \in \mathcal{D}$. Therefore, $\mathcal{D}$ is a $d$-system containing the $\pi$-system $\mathcal{A}$ so by Dynkin's lemma is equal to $\mathcal{E}$.

:::

We now want to show that Lebesgue measure is the only which assigns each interval the correct measure.

::: {.proposition}

Lebesgue measure is the only measure on $(\mathbb{R}, \mathcal{B}(\mathbb{R}))$ which assigns each half open interval its length. This is equally true with half open hyper-rectangles in $\mathbb{R}^d$.

:::

::: {.proof}

The collection of half open intervals is a $\pi$-system which generates the Borel $\sigma$-algebra. Therefore, if $\lambda(\mathbb{R})$ had been finite we could use Dynkin's uniqueness of extension Lemma to get that any other measure which agrees with Lebesgue measure on the half open intervals must agree with Lebesgue measure on the whole of the Borel $\sigma$-algebra. Instead let $E_n = (-n,n]^d$ then, by Dynkin's uniqueness of extension lemma we have that $\lambda$ is the only measure on $E_n$, assigning each rectangle inside $E_n$ its measure. That is to say if $\mu$ is another measure on $\mathbb{R}^d$ which agrees with Lebesgue measure on rectangles then it agrees with Lebesgue measure on every Borel set which is a subset of $E_n$.


 We also have that, for any $A \in \mathcal{B}(\mathbb{R})$, $\mu(A) = \lim_n \mu(A \cap E_n)$ by continuity of measure. By the argument above $\mu(A_n) = \lambda(A_n)$ for each $n$ as $A_n \subset E_n$ and is Borel. So $\mu(A) = \lim_n \mu(A\cap E_n) = \lim_n \lambda(A \cap E_n) = \lambda(A)$.

:::

## Properties of Lebesgue measure

This collection is a section of facts about Lebesgue measure and the set of Lebesgue measurable sets. We start with looking at $\mathscr{M}$ the $\sigma$-algebra of Lebesgue measurable sets. We call sets with $\lambda*(A)=0$ null sets.

::: {.lemma name="Null sets are all Lebesgue measurable"}

If $A$ in $\mathscr{P}(\mathbb{R})$ and $\lambda^*(A) =0$ then $A \in \mathscr{M}$.

:::

::: {.proof}

This is on the week 2 exercise sheet. 

:::


The most important thing we want to prove about $\mathscr{M}$ is that there exists a non-Lebesgue measurable set. Before we do this we need to explore a few more properties of Lebesgue measure itself.

::: {.proposition}

Lebesgue measure is *regular* that is to say

- $$\lambda(A) = \inf \{ \lambda(U)\,:\, \mbox{U is open}, A \subseteq U\},$$
- $$\lambda(A) = \sup \{ \lambda(K)\,:\, \mbox{K is compact}, K \subseteq A\}.$$

:::

::: {.proof}

By monotonicity we can see that $$\lambda(A) \leq \inf \{ \lambda(U)\,:\, \mbox{U is open}, A \subseteq U\}.$$ 
Furthermore we can find a sequence of half open rectangles $R_k$ such that $A \subseteq \bigcup_n R_n$ and $\sum_n \lambda(R_n) \leq \lambda(A) + \epsilon$. By slightly enlarging each of the half open rectangles we can produce another sequence of fully open rectangles $\tilde{R}_n$ such that $A \subseteq \bigcup_n \tilde{R}_n$ and $\lambda(A) \geq \sum_n \lambda(\tilde{R}_n)-2\epsilon$. The set, $\bigcup_n \tilde{R}_n$ is open and $\epsilon$ can be made arbitrarily small so this shows $$\lambda(A) \geq \inf \{ \lambda(U)\,:\, \mbox{U is open}, A \subseteq U\}.$$

Monotonicity shows that $$\lambda(A) \geq \sup \{ \lambda(K)\,:\, \mbox{K is compact}, K \subseteq A\}.$$ First let us assume that $A$ is contained in some ball, $B$ around 0. Now use the first part to find some open set $U$ such that $B \setminus A \subseteq U$ and $\lambda(U) \leq \lambda(B \setminus A) + \epsilon$. Now let $K = B \setminus U$ then we have $K \subseteq A \subseteq B$ and $\lambda(K) \geq \lambda(B) - \lambda(U) \geq \lambda(B) - \lambda(B \setminus A) - \epsilon = \lambda(A) - \epsilon$ (here we use the fact that $B, A, U, K$ will all have finite measure as they are inside $B$). As $\epsilon$ is arbitrary this concludes the proof when $A$ is contained in a ball. 

Now suppose that $A$ is unbounded. Then let $A_n = A \cap B_n$ where $B_n$ is the closed ball of radius $n$. We have that $\lambda(A_n) \rightarrow \lambda(A)$. If $\lambda(A) = \infty$ then we can find $K_n \subseteq A_n$ with $\lambda(K_n)$ arbitrarily close to $\lambda(A_n)$ therefore we can find such a sequence with $\lambda(K_n) \rightarrow \infty$. If $\lambda(A) \neq \infty$ then, given $\epsilon$, there exists $N$ such that $\lambda(A_n) \geq \lambda(A)-\epsilon$ for $n \geq N$. Then we can find $K_N \subseteq A_N$ such that $\lambda(K_n) \geq \lambda(A_N) - \epsilon$ therefore $\lambda(K_N) \geq \lambda(A)- 2 \epsilon$. This shows we can a compact set which is contained in $A$, with measure arbitrarily close to that of $A$. 

:::

We now want to recall that Lebesgue measure is the unique measure which assigns half open intervals (rectangles...) the correct length.

::: {.corollary}

Lebesgue measure is translation invariant on $\mathbb{R}$. That is to say if we define the set $x+A = \{ x+y, y \in A\}$ then $\lambda(x+A) = \lambda(A)$

:::

::: {.proof}

Define a new measure $\lambda_x$ by $\lambda_x(A) = \lambda(x+A)$ then $\lambda_x((a,b]) = \lambda((a+x,b+x]) = b+x -(a+x) = b-a$. Therefore $\lambda_x$ agrees with $\lambda$ on the half open intervals and therefore agrees with $\lambda$ on the whole of $\mathcal{B}(\mathbb{R})$. Again it is straightforward to extend this to $\mathbb{R}^d$.

:::

Now we can use regularity of Lebesgue measure in order to characterise the sets in $\mathscr{M}$ (we can also do this in other ways as seen on the exercise sheet).

::: {.proposition}
If $A$ is in $\mathscr{M}$ then there exists $B \in \mathcal{B}(\mathbb{R})$ and $N$ a null set such that $A= B \cup N$ and this is a disjoint union.

:::

::: {.proof}

Suppose first that $\lambda(A)< \infty$ by the second part of the regularity of Lebesgue measure result we have that 
\[\lambda(A) = \sup\{ \lambda(K) \,:\, \mbox{K compact}, K \subseteq A\}. \] 
Therfore for each $n$ we can find $K_n$ such that $K_n \subseteq A$, $K_n$ is compact and $\lambda(K_n) \geq \lambda(A)-1/n$. Then let $B = \bigcup_n K_n$. 

Then as each $K_n$ is compact it is a Borel set and so $B$ is a countable union of Borel sets so also a Borel set. We also have $B \subseteq A$ so $\lambda(B) \leq \lambda(A)$ and $K_n \subseteq B$ so $\lambda(B)\geq \lambda(K_n) \geq \lambda(A)-1/n$ for each $n$. Therefore $\lambda(B) = \lambda(A)$. Now let $N= A \setminus B$ then $\lambda(N) = \lambda(A) - \lambda(B)=0$ so $N$ is a null set. This gives our result for $\lambda(A) < \infty$.

If $\lambda(A) = \infty$ then split $\mathbb{R}$ into a countable union of sets with finite Lebesgue measure $E_n$ for example $E_n = [n, n+1)\cup [-n-1,-n)$. Then set $A_n = A \cap E_n$. Then $\lambda(A_n) < \infty$ so there exists a Borel set $B_n$ and a null set $N_n$ such that $A_n = B_n \cup N_n$ and these sets are disjoint. Now set $B = \bigcup_n B_n$ and $N = \bigcup_n N_n$. $B$ is a Borel set as it's the countable union of Borel sets. $\lambda(N) = \sum_n \lambda(N_n) = 0$ so $N$ is a null set. Lastly $B$ and $N$ are disjoint as all the $E_n$ are disjoint so we can't have that $B_n$ has points in common with $N_{n'}$ for $n \neq n'$ as they will be in different $E_n$. Therefore we can write $A$ as $B \cup N$ with this being a disjoint union.

:::

We can use this to show that $\lambda$ is translation invariant on $\mathscr{M}$ not just on $\mathcal{B}(\mathbb{R}^d)$ to do this we need to show that the translation of a null set is also null.

::: {.lemma}

If $N$ is a null set then $x+N = \{ x+y \,:\, y \in N\}$ is also null

:::

::: {.proof}

We know that $0 = \lambda^*(N) = \inf_{(I_n)_n \in \mathcal{C}(N)}\sum_n \lambda(I_n)$ so for a given $\epsilon > 0$ we can find a sequence $(I_n)_n$ such that $N \subseteq \bigcup_n I_n$ and $\sum_n \lambda(I_n) \leq \epsilon$. Now if we shift everything we can see that $x+ I_n$ is still a half open interval for each $n$ and $x+N \subseteq \bigcup_n (x+I_n)$ so $\lambda^*(x+N) \leq \sum_n \lambda(x+I_n)$ and $\lambda(x+ I_n) = \lambda(I_n)$ for each $n$ so $\lambda^*(x+N) \leq \sum_n \lambda (I_n) \leq \epsilon$. Therefore the Lebesgue outer measure of $x+N$ can be made arbitrarily small so it must be 0. 

:::

Now we can prove translation invariance

::: {.proposition}

If $A \in \mathscr{M}$ then $x+A \in \mathscr{M}$ and $\lambda(x+A)=\lambda(A)$.

:::

::: {.proof}

We've shown that $A$ can be expressed as a disjoint union of a Borel set and a null set. So $A = B \cup N$. This means that $x+A = (x+B) \cup (x+N)$ then $(x+B)$ is a Borel set and $(x+N)$ is a null set so $x+A$ is the union of two sets in $\mathscr{M}$ so also in $\mathscr{M}$. Furthermore $\lambda(x+A) = \lambda(x+B) + \lambda(x+N)$. We know that Lebesgue measure is translation invariant on the Borel sets and that the translation of a null set is null so this gives
\[ \lambda(x+A) = \lambda(x+B)+\lambda(x+N)= \lambda(B) = \lambda(B\cup N)= \lambda(A).  \]

:::



Lastly, in the construction of Lebesgue measure we show that $\mathscr{M}$ is not the whole of $\mathscr{P}(\mathbb{R})$ and that there exist non-Lebesgue measureable sets.

::: {.proposition}

There exists sets that are in $\mathscr{P}(\mathbb{R})$ which are not in $\mathscr{M}$. This result is due to Vitali and the set we construct is often called the *Vitali set*

:::

::: {.proof}

This proof involves the use of the axiom of choice. In fact it is known that it is necessary to use some form of the axiom of choice to prove the existence of a non-Lebesgue measurable set in $\mathbb{R}$.

We use an argument by contradiction, we begin by assuming every subset of $\mathbb{R}$ is Lebesgue measurable. We define an equivalence relation on $[0,1)$ by saying $x \sim y$ exactly when $x-y \in \mathbb{Q}$.  Using the axiom of choice we find a subset $S$ of $[0,1)$ which contains exactly one representative of each equivalence class. Next we define the set $S_q = \{ s+q \, (\mbox{mod}\,1) \, : \, s \in S \}$ for each $q \in \mathbb{Q} \cap [0,1)$. Then by our choice of $S$ we have that

$$ [0,1) = \bigcup_{q \in \mathbb{Q} \cap [0,1)} (S_q), $$
where this union is disjoint. We can check see that $S_q \cap S_{q'} = \emptyset$ for $q \neq q'$ as if $x$ was in both then there exists $y, y' \in S$ such that $x = y +q \,(mod 1)$ and $x= y' + q' (mod 1)$ this means $y - y' \in \mathbb{Q}\setminus\{0\}$ which is a contradiction to the fact that $S$ contains exactly one member of each equivalence class. Also we can see that this union contains every element of $[0,1)$ since if $x \in [0,1)$ there exists some $y$ which is in the same equivalence class of $x$ with $y \in S$. Therefore $x = y + q \,(mod 1)$ for some $q \in \mathbb{Q}\cap [0,1)$ so $x \in S_q$ for this $q$.


We can also see by translation invariance of $\lambda$ that if $S$ were Lebesgue measurable then we would have

$$ \lambda(S) = \lambda(S+q) $$
for every $q$. Therefore, by countable additivity we would have

$$ \lambda([0,1)) = \sum_{q \in \mathbb{Q} \cap [0,1)} \lambda (S+q) = \sum_{q \in \mathbb{Q} \cap [0,1)} \lambda(S) = \infty. $$

:::



