# Summary of the course and list of important theorems

This section is primarily intended to help you prepare for the exam. Questions on the exam are split into three types (only visible on the solutions). These are bookwork, seen and unseen. 

Bookwork comprises material I expect you to know by heart, or be able to reproduce to look like that in the course. This includes all definitions and the statements and proofs of most named theorems in the course. I'm afraid measure theory is a naturally bookwork heavy course. I'm not expecting you to learn all of these by heart but I am hoping you will be able to reproduce the majority of any proof in the exam. Look at previous exams to get an idea of what is expected. 

Seen material includes everything in the lecture notes, assignments or exercise sheets which isn't bookwork. I expect you to find it easier to answer questions where you have seen the question or something almost identical before. Therefore its helpful to be familiar with all this before the exam. 

Unseen material will be problem based questions that are similar, but substantially different, to questions on the exercise sheets or worked examples, or theorems from the course. 

Below is a list of the key material from the course. Anything which is a definition should be considered bookwork, or anything where I've written +proof, should be considered bookwork. I've also recorded some results where I expect you to know the statement but not the theorem.

## Sigma algebras and measures

 - Definition of a sigma algebra
 - What is means to say a sigma-algebra is generated by a collection of sets
 - Definition of Borel sigma-algebra
 - Examples of sets generating $\mathcal{B}(\mathbb{R})$ + proof
 - $\pi$-systems and $d$-systems and the statement of Dynkin's lemma
 - Definition of a measure
 - Definition of countable subadditivity and monotonicity
 - Definition of a measure space
 - Definition Finite and sigma-finite measure spaces
 - Continuity of measure theorem
 
## Lebesgue measure

- Definition of Lebesgue outer measure
- Definition of a Lebesgue measurable set plus some knowledge of the proof they form a sigma algebra
- Lebesgue measure restricted to the Lebesgue measurable sets is a measure
- Borel sets are Lebesgue measurable + proof
- Uniqueness of extension, how to apply it to sigma-finite spaces and uniqueness of Lebesgue measure in particular, some idea of the proof
- Translation invariance of Lebesgue measure + proof
- Null sets are Lebesgue measurable + proof
- Characterisation of Lebesgue measurable sets as null set + Borel and some notion of the proof of this
- Regularity of Lebesgue measure + proof
- Existence of a non-Lebesgue measurable set (Vitali set) + proof

## Measurable functions

- Definition of a measurable function plus use of generating sets to prove functions are measurable
- Continuous functions are Borel measurable + proof
- Monotone functions from $\mathbb{R}$ to $\mathbb{R}$ are Borel measurable + proof
- Compositions of measurable function are measurable
- Definition of image measure and some notions of Theorem 4.1
- Definition of almost everywhere convergence
- Definition of convergence in measure
-Quasiequivalence of convergence (Theorem 4.2) + proof
- Egoroff's Theorem + proof
- Lusin's Theorem + proof 

## Integration

- Definition of a simple function
- Definition of the integral of a simple function
- Definition of the integral of a non-negative function
- Definition of the integral of an integrable function
- Monotone convergence theorem + the main ideas of the proof (Its too long to get you to repeat it in full but you should be familiar with it)
- Working with non-negative functions by approximating by simple functions
- Beppo-Levi + proof
- Fatou's lemma + proof
- Dominated convergence + proof
- Some knowledge of how to differentiate under the integral sign
- Some knowledge of how to prove the change of variables formula
- Main ideas to show that Riemann integrable imples Lebesgue measurable and the integrals agree (again its too long to repeat in full but you should be familiar with the steps)

## Norms and Inequalities
- Definition of $L^p(E)$ and $\|\cdot\|_p$ norm
- Holder's inequality +proof
- Minkowski's inequality + proof
- Markov's inequality +proof
- Jensen's inequality (+idea of the proof)
- Completeness of $L^p(E)$ + proof
- Density of step functions and continuous functions in $L^p(E)$

## Product Measure
- Definition of the product sigma-algebra and knowlege of associated small lemmas
- Characterisation, existence and uniqueness of product measure in sigma-finite spaces (Theorem 7.1)+ proof
- Fubini-Tonelli for positive functions + proof
- Fubini-Tonelli for integrable functions + proof
- Ideas from the applications of product measure section.

## Radon-Nikodym Theorem
- Definition of finite signed measure
- Definition of positive and negative sets
- Hahn Decomposition theorem + proof
- Jordan Decompositino theorem + proof
- Definition of absolute continuity
- Radon-Nikodym theorem + main ideas of the proof